version: '3.8'

services:
  mysqldb:
    platform: linux
    image: mysql:8.4.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_USER=$DOCKER_ROOT_USER
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: unless-stopped
    image: winehood
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:$DB_DOCKER_PORT/$DB_NAME",
        "spring.datasource.username": "$DOCKER_ROOT_USER",
        "spring.datasource.password": "$DB_PASSWORD"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
