name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Create .env file
        run: |
          echo "JWT_EXPIRATION=${{secrets.JWT_EXPIRATION}}" >> .env
          echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> .env
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
